# Generated by Django 2.1.2 on 2019-03-15 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_hours_in_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='hours_in_day',
            new_name='work_day_hours',
        ),
    ]
