# Generated by Django 2.1.2 on 2019-01-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20181104_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.TimeField(),
        ),
    ]
