# Generated by Django 2.1.2 on 2019-03-11 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='global_hours_in_day',
            field=models.IntegerField(default=8),
        ),
    ]
