# Generated by Django 2.1.2 on 2019-03-15 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_global_hours_in_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='global_hours_in_day',
            new_name='global_work_day_hours',
        ),
    ]
